<?php

namespace ContainerL8zrIxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MV072pOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mV072pO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mV072pO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objetosalmacenRepository' => ['privates', 'App\\Repository\\ObjetosalmacenRepository', 'getObjetosalmacenRepositoryService', true],
        ], [
            'objetosalmacenRepository' => 'App\\Repository\\ObjetosalmacenRepository',
        ]);
    }
}
