<?php

namespace ContainerL8zrIxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Di8OLLGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.di8OLLG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.di8OLLG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'registroentrada' => ['privates', '.errored..service_locator.di8OLLG.App\\Entity\\Registroentrada', NULL, 'Cannot autowire service ".service_locator.di8OLLG": it references class "App\\Entity\\Registroentrada" but no such service exists.'],
        ], [
            'registroentrada' => 'App\\Entity\\Registroentrada',
        ]);
    }
}
