<?php

namespace ContainerL8zrIxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lgsa7LFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lgsa7LF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lgsa7LF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'registrosalida' => ['privates', '.errored..service_locator.Lgsa7LF.App\\Entity\\Registrosalida', NULL, 'Cannot autowire service ".service_locator.Lgsa7LF": it references class "App\\Entity\\Registrosalida" but no such service exists.'],
        ], [
            'registrosalida' => 'App\\Entity\\Registrosalida',
        ]);
    }
}
