<?php

namespace ContainerL8zrIxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GIj2h5AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gIj2h5A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gIj2h5A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'registroentrada' => ['privates', '.errored..service_locator.gIj2h5A.App\\Entity\\Registroentrada', NULL, 'Cannot autowire service ".service_locator.gIj2h5A": it references class "App\\Entity\\Registroentrada" but no such service exists.'],
            'registroentradaRepository' => ['privates', 'App\\Repository\\RegistroentradaRepository', 'getRegistroentradaRepositoryService', true],
        ], [
            'registroentrada' => 'App\\Entity\\Registroentrada',
            'registroentradaRepository' => 'App\\Repository\\RegistroentradaRepository',
        ]);
    }
}
