<?php

namespace ContainerL8zrIxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistroentrada2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gIj2h5A.App\Entity\Registroentrada' shared service.
     *
     * @return \App\Entity\Registroentrada
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gIj2h5A": it references class "App\\Entity\\Registroentrada" but no such service exists.');
    }
}
