<?php

namespace ContainerUwIy2HI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5g281bXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5g281bX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5g281bX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.lY9iYQV', 'get_ServiceLocator_LY9iYQVService', true],
            'App\\Controller\\ObjetosalmacenController::delete' => ['privates', '.service_locator.dRBh5DZ', 'get_ServiceLocator_DRBh5DZService', true],
            'App\\Controller\\ObjetosalmacenController::edit' => ['privates', '.service_locator.dRBh5DZ', 'get_ServiceLocator_DRBh5DZService', true],
            'App\\Controller\\ObjetosalmacenController::index' => ['privates', '.service_locator.mV072pO', 'get_ServiceLocator_MV072pOService', true],
            'App\\Controller\\ObjetosalmacenController::new' => ['privates', '.service_locator.mV072pO', 'get_ServiceLocator_MV072pOService', true],
            'App\\Controller\\ObjetosalmacenController::show' => ['privates', '.service_locator.F6vI5JM', 'get_ServiceLocator_F6vI5JMService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\RegistroentradaController::delete' => ['privates', '.service_locator.gIj2h5A', 'get_ServiceLocator_GIj2h5AService', true],
            'App\\Controller\\RegistroentradaController::edit' => ['privates', '.service_locator.gIj2h5A', 'get_ServiceLocator_GIj2h5AService', true],
            'App\\Controller\\RegistroentradaController::index' => ['privates', '.service_locator.ewrtalK', 'get_ServiceLocator_EwrtalKService', true],
            'App\\Controller\\RegistroentradaController::new' => ['privates', '.service_locator.ewrtalK', 'get_ServiceLocator_EwrtalKService', true],
            'App\\Controller\\RegistroentradaController::show' => ['privates', '.service_locator.di8OLLG', 'get_ServiceLocator_Di8OLLGService', true],
            'App\\Controller\\RegistrosalidaController::delete' => ['privates', '.service_locator.jyYEYZ3', 'get_ServiceLocator_JyYEYZ3Service', true],
            'App\\Controller\\RegistrosalidaController::edit' => ['privates', '.service_locator.jyYEYZ3', 'get_ServiceLocator_JyYEYZ3Service', true],
            'App\\Controller\\RegistrosalidaController::index' => ['privates', '.service_locator.VeATVQq', 'get_ServiceLocator_VeATVQqService', true],
            'App\\Controller\\RegistrosalidaController::new' => ['privates', '.service_locator.VeATVQq', 'get_ServiceLocator_VeATVQqService', true],
            'App\\Controller\\RegistrosalidaController::show' => ['privates', '.service_locator.Lgsa7LF', 'get_ServiceLocator_Lgsa7LFService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.lY9iYQV', 'get_ServiceLocator_LY9iYQVService', true],
            'App\\Controller\\ObjetosalmacenController:delete' => ['privates', '.service_locator.dRBh5DZ', 'get_ServiceLocator_DRBh5DZService', true],
            'App\\Controller\\ObjetosalmacenController:edit' => ['privates', '.service_locator.dRBh5DZ', 'get_ServiceLocator_DRBh5DZService', true],
            'App\\Controller\\ObjetosalmacenController:index' => ['privates', '.service_locator.mV072pO', 'get_ServiceLocator_MV072pOService', true],
            'App\\Controller\\ObjetosalmacenController:new' => ['privates', '.service_locator.mV072pO', 'get_ServiceLocator_MV072pOService', true],
            'App\\Controller\\ObjetosalmacenController:show' => ['privates', '.service_locator.F6vI5JM', 'get_ServiceLocator_F6vI5JMService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\RegistroentradaController:delete' => ['privates', '.service_locator.gIj2h5A', 'get_ServiceLocator_GIj2h5AService', true],
            'App\\Controller\\RegistroentradaController:edit' => ['privates', '.service_locator.gIj2h5A', 'get_ServiceLocator_GIj2h5AService', true],
            'App\\Controller\\RegistroentradaController:index' => ['privates', '.service_locator.ewrtalK', 'get_ServiceLocator_EwrtalKService', true],
            'App\\Controller\\RegistroentradaController:new' => ['privates', '.service_locator.ewrtalK', 'get_ServiceLocator_EwrtalKService', true],
            'App\\Controller\\RegistroentradaController:show' => ['privates', '.service_locator.di8OLLG', 'get_ServiceLocator_Di8OLLGService', true],
            'App\\Controller\\RegistrosalidaController:delete' => ['privates', '.service_locator.jyYEYZ3', 'get_ServiceLocator_JyYEYZ3Service', true],
            'App\\Controller\\RegistrosalidaController:edit' => ['privates', '.service_locator.jyYEYZ3', 'get_ServiceLocator_JyYEYZ3Service', true],
            'App\\Controller\\RegistrosalidaController:index' => ['privates', '.service_locator.VeATVQq', 'get_ServiceLocator_VeATVQqService', true],
            'App\\Controller\\RegistrosalidaController:new' => ['privates', '.service_locator.VeATVQq', 'get_ServiceLocator_VeATVQqService', true],
            'App\\Controller\\RegistrosalidaController:show' => ['privates', '.service_locator.Lgsa7LF', 'get_ServiceLocator_Lgsa7LFService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\ObjetosalmacenController::delete' => '?',
            'App\\Controller\\ObjetosalmacenController::edit' => '?',
            'App\\Controller\\ObjetosalmacenController::index' => '?',
            'App\\Controller\\ObjetosalmacenController::new' => '?',
            'App\\Controller\\ObjetosalmacenController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistroentradaController::delete' => '?',
            'App\\Controller\\RegistroentradaController::edit' => '?',
            'App\\Controller\\RegistroentradaController::index' => '?',
            'App\\Controller\\RegistroentradaController::new' => '?',
            'App\\Controller\\RegistroentradaController::show' => '?',
            'App\\Controller\\RegistrosalidaController::delete' => '?',
            'App\\Controller\\RegistrosalidaController::edit' => '?',
            'App\\Controller\\RegistrosalidaController::index' => '?',
            'App\\Controller\\RegistrosalidaController::new' => '?',
            'App\\Controller\\RegistrosalidaController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\ObjetosalmacenController:delete' => '?',
            'App\\Controller\\ObjetosalmacenController:edit' => '?',
            'App\\Controller\\ObjetosalmacenController:index' => '?',
            'App\\Controller\\ObjetosalmacenController:new' => '?',
            'App\\Controller\\ObjetosalmacenController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistroentradaController:delete' => '?',
            'App\\Controller\\RegistroentradaController:edit' => '?',
            'App\\Controller\\RegistroentradaController:index' => '?',
            'App\\Controller\\RegistroentradaController:new' => '?',
            'App\\Controller\\RegistroentradaController:show' => '?',
            'App\\Controller\\RegistrosalidaController:delete' => '?',
            'App\\Controller\\RegistrosalidaController:edit' => '?',
            'App\\Controller\\RegistrosalidaController:index' => '?',
            'App\\Controller\\RegistrosalidaController:new' => '?',
            'App\\Controller\\RegistrosalidaController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
