<?php

namespace ContainerUwIy2HI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DRBh5DZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dRBh5DZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dRBh5DZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objetosalmacen' => ['privates', '.errored..service_locator.dRBh5DZ.App\\Entity\\Objetosalmacen', NULL, 'Cannot autowire service ".service_locator.dRBh5DZ": it references class "App\\Entity\\Objetosalmacen" but no such service exists.'],
            'objetosalmacenRepository' => ['privates', 'App\\Repository\\ObjetosalmacenRepository', 'getObjetosalmacenRepositoryService', true],
        ], [
            'objetosalmacen' => 'App\\Entity\\Objetosalmacen',
            'objetosalmacenRepository' => 'App\\Repository\\ObjetosalmacenRepository',
        ]);
    }
}
