<?php

namespace ContainerUwIy2HI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F6vI5JMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F6vI5JM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F6vI5JM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objetosalmacen' => ['privates', '.errored..service_locator.F6vI5JM.App\\Entity\\Objetosalmacen', NULL, 'Cannot autowire service ".service_locator.F6vI5JM": it references class "App\\Entity\\Objetosalmacen" but no such service exists.'],
        ], [
            'objetosalmacen' => 'App\\Entity\\Objetosalmacen',
        ]);
    }
}
