<?php

namespace ContainerUwIy2HI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JyYEYZ3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jyYEYZ3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jyYEYZ3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'registrosalida' => ['privates', '.errored..service_locator.jyYEYZ3.App\\Entity\\Registrosalida', NULL, 'Cannot autowire service ".service_locator.jyYEYZ3": it references class "App\\Entity\\Registrosalida" but no such service exists.'],
            'registrosalidaRepository' => ['privates', 'App\\Repository\\RegistrosalidaRepository', 'getRegistrosalidaRepositoryService', true],
        ], [
            'registrosalida' => 'App\\Entity\\Registrosalida',
            'registrosalidaRepository' => 'App\\Repository\\RegistrosalidaRepository',
        ]);
    }
}
