<?php

namespace ContainerUwIy2HI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LY9iYQVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lY9iYQV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lY9iYQV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objetoRepo' => ['privates', 'App\\Repository\\ObjetosalmacenRepository', 'getObjetosalmacenRepositoryService', true],
        ], [
            'objetoRepo' => 'App\\Repository\\ObjetosalmacenRepository',
        ]);
    }
}
