<?php

namespace ContainerUwIy2HI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjetosalmacenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F6vI5JM.App\Entity\Objetosalmacen' shared service.
     *
     * @return \App\Entity\Objetosalmacen
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.F6vI5JM": it references class "App\\Entity\\Objetosalmacen" but no such service exists.');
    }
}
