<?php

namespace ContainerUwIy2HI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrosalida2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jyYEYZ3.App\Entity\Registrosalida' shared service.
     *
     * @return \App\Entity\Registrosalida
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jyYEYZ3": it references class "App\\Entity\\Registrosalida" but no such service exists.');
    }
}
