<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL8zrIxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL8zrIxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL8zrIxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL8zrIxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL8zrIxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'L8zrIxx',
    'container.build_id' => '77b921d8',
    'container.build_time' => 1678475651,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL8zrIxx');
